#!/bin/bash

source .src

pair=7
P=$(( pair % 8 + 1 ))
stepN=64
fromN=$(( 512 + P ))
toN=$(( 1024 + 512 + P ))
C=4 # Mejor número de hilos de las obtenidas anteriormente
serialOp=1 # Serial mode in mult.c
parallelOp=4 # Mejor versión de las disponibles (ver switch() en mult.c)
nLoops=10

info "P = $P\n"
info "fromN = $fromN\n"
info "stepN = $stepN\n"
info "nLoops = $nLoops\n"
info "toN = $toN\n"

fDAT_1="speedup.dat"
fPNG_1="speedup.png"

fDAT_2="time.dat"
fPNG_2="time.png"

fDAT=
fPNG=

xLabel=
yLabel=

plotall() {

  echo "Generating plot..."

# llamar a gnuplot para generar el gráfico y pasarle directamente por la entrada
# estándar el script que está entre "<< END_GNUPLOT" y "END_GNUPLOT"
gnuplot << END_GNUPLOT
set title "Matrix multiplication time comparison"
set ylabel "Time (s)"
set encoding utf8
set xlabel "Vector size"
set key right bottom
set grid
set term png
set output "$fPNG_2"

plot  "$fDAT_2" using 1:3 with lines lc "blue" lw 2 dashtype 1 title 'parallel mult', \
      "$fDAT_2" using 1:2 with lines lc "orange" lw 2 dashtype 0 title 'serial mult'

set title "Matrix multiplication speedup"
set ylabel "Speedup"
set encoding utf8
set xlabel "Vector size"
set key right bottom
set grid
set term png
set output "$fPNG_1"

plot "$fDAT_1" using 1:2 with lines lc "orange" lw 2 title "speedup mult"

replot
quit
END_GNUPLOT

}

info "running tests ...\n"

for ((N = fromN ; N <= toN ; N += stepN)); do

    info "testing N [$N,$toN] ...\n"

    serialTime="0"
    parallelTime="0"
    speedup="0"

    serialMultSum="0"
    parallelMultSum="0"

    # time test
    for (( i=0 ; i < $nLoops; i +=1 )); do
      echo -n "loop=$i; serialMultTime@$N: "
      serialMultTime=$(./mult $N $serialOp | grep 'time' | awk '{print $3}')
      echo "${serialMultTime}s"
      echo -n "loop=$i; parallelMultTime@$N: "
      parallelMultTime=$(./mult $N $parallelOp $C | grep 'time' | awk '{print $3}')
      echo "${parallelMultTime}s"
      
      serialMultSum=$(calc "$serialMultSum+$serialMultTime")
      parallelMultSum=$(calc "$parallelMultSum+$parallelMultTime")
    done

    serialMultTime=$(calc "$serialMultSum/$nLoops")
    parallelMultTime=$(calc "$parallelMultSum/$nLoops")

    info "serialTimeAvg: $serialMultTime\n"
    info "parallelTimeAvg: $parallelMultTime\n"

    x=$(calc "$serialMultTime/$parallelMultTime")

    echo "Calculated: $x"

    if [ $? -ne 0 ]; then
      speedup="0"
    else
      speedup="$x"
    fi

    info "speedup: $speedup\n"

    echo "$N $speedup" >> $fDAT_1
    echo "$N $serialMultTime $parallelMultTime" >> $fDAT_2
done

plotall
success "done\n"